"""
PDF report generator for civilTools — full English structural report.

Uses fpdf2 with matplotlib LaTeX rendering.  Accepts a ``ReportData``
instance and renders every active section to a styled PDF document.
"""

from __future__ import annotations

import io
import tempfile
from pathlib import Path
from typing import Any

import matplotlib
from fpdf import FPDF

from civiltools.report.report_config import ReportConfig
from civiltools.report.strings import get_string, ASCE7_IRREGULARITY_DESC
from civiltools.report.data_extractor import ReportData


# ── Farsi → English translations ──────────────────────────────────────────
_RISK_EN = {
    "\u06a9\u0645": "Low",
    "\u0645\u062a\u0648\u0633\u0637": "Moderate",
    "\u0632\u06cc\u0627\u062f": "High",
    "\u062e\u06cc\u0644\u06cc \u0632\u06cc\u0627\u062f": "Very High",
}

def _en_risk(risk_level) -> str:
    return _RISK_EN.get(str(risk_level), str(risk_level))

def _en_soil(soil_type) -> str:
    return f"Type {soil_type}" if soil_type else ""


# ═══════════════════════════════════════════════════════════════════════════
# LaTeX rendering
# ═══════════════════════════════════════════════════════════════════════════

def _render_latex(latex_str: str, dpi: int = 150, fontsize: int = 14) -> bytes:
    """Render a LaTeX string to PNG bytes using matplotlib."""
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    fig, ax = plt.subplots(figsize=(8, 1.2))
    ax.axis("off")
    ax.text(0.5, 0.5, f"${latex_str}$",
            fontsize=fontsize, ha="center", va="center",
            transform=ax.transAxes)
    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=dpi, bbox_inches="tight",
                transparent=True, pad_inches=0.1)
    plt.close(fig)
    buf.seek(0)
    return buf.read()


# ═══════════════════════════════════════════════════════════════════════════
# EnglishPDF
# ═══════════════════════════════════════════════════════════════════════════

class EnglishPDF(FPDF):
    """PDF builder for English LTR structural engineering reports."""

    def __init__(self, config: ReportConfig | None = None):
        super().__init__()
        self.config = config or ReportConfig(language="en")
        self._temp_files: list[Path] = []
        self._font_name = self._register_unicode_font()
        self._setup_defaults()

    @staticmethod
    def _find_dejavu() -> Path | None:
        """Locate DejaVu Sans TTF shipped with matplotlib."""
        try:
            ttf = Path(matplotlib.get_data_path()) / "fonts" / "ttf" / "DejaVuSans.ttf"
            if ttf.exists():
                return ttf
        except Exception:
            pass
        return None

    def _register_unicode_font(self) -> str:
        """Add a Unicode TTF font to the PDF and return its family name."""
        ttf = self._find_dejavu()
        if ttf is not None:
            self.add_font("DejaVu", "", str(ttf))
            self.add_font("DejaVu", "B", str(ttf.parent / "DejaVuSans-Bold.ttf"))
            return "DejaVu"
        # Fallback: built-in Helvetica (latin-1 only)
        return "Helvetica"

    def _setup_defaults(self):
        self.set_auto_page_break(auto=True, margin=20)
        self.set_margins(15, 15, 15)

    # ── Header / Footer ───────────────────────────────────────────────
    def header(self):
        self.set_font(self._font_name, "B", 9)
        self.set_text_color(100, 100, 100)
        self.cell(0, 8, "civilTools - Structural Engineering Report", align="C")
        self.ln(10)
        self.set_draw_color(200, 200, 200)
        self.line(15, self.get_y(), self.w - 15, self.get_y())
        self.ln(3)

    def footer(self):
        if self.config.include_page_numbers:
            self.set_y(-15)
            self.set_font(self._font_name, "", 8)
            self.set_text_color(128, 128, 128)
            self.cell(0, 10, f"Page {self.page_no()}/{{nb}}", align="C")

    # ── Content builders ──────────────────────────────────────────────
    def add_title_page(self, title: str, subtitle: str = ""):
        self.add_page()
        self.ln(60)
        self.set_font(self._font_name, "B", 28)
        self.set_text_color(30, 60, 120)
        self.cell(0, 15, title, align="C")
        self.ln(20)
        if subtitle:
            self.set_font(self._font_name, "", 16)
            self.set_text_color(80, 80, 80)
            self.cell(0, 10, subtitle, align="C")
            self.ln(15)
        self.set_font(self._font_name, "", 10)
        self.set_text_color(140, 140, 140)
        self.cell(0, 10, "Generated by civilTools", align="C")
        self.set_text_color(0, 0, 0)

    def add_heading(self, text: str, level: int = 1):
        sizes = {1: 18, 2: 14, 3: 12}
        colors = {1: (30, 60, 120), 2: (50, 100, 50), 3: (80, 80, 80)}
        self.ln(6)
        self.set_font(self._font_name, "B", sizes.get(level, 12))
        self.set_text_color(*colors.get(level, (0, 0, 0)))
        self.cell(0, 10, text, new_x="LMARGIN", new_y="NEXT")
        if level == 1:
            self.set_draw_color(30, 60, 120)
            self.line(15, self.get_y(), self.w - 15, self.get_y())
        self.ln(3)
        self.set_text_color(0, 0, 0)

    def add_paragraph(self, text: str, bold: bool = False):
        style = "B" if bold else ""
        self.set_font(self._font_name, style, 11)
        self.multi_cell(0, 6, text)
        self.ln(3)

    def add_kv_table(self, rows: list[tuple[str, str]]):
        col_w = [70, self.w - 30 - 70]
        self.set_font(self._font_name, "", 10)
        fill = False
        for key, val in rows:
            if fill:
                self.set_fill_color(240, 245, 250)
            self.cell(col_w[0], 7, key, border="LR", fill=fill)
            self.cell(col_w[1], 7, str(val), border="LR", fill=fill)
            self.ln()
            fill = not fill
        self.ln(4)

    def add_data_table(self, headers: list[str], rows: list[list],
                       col_widths: list[float] | None = None):
        n = len(headers)
        available = self.w - 30
        if col_widths is None:
            col_widths = [available / n] * n

        # Header
        self.set_font(self._font_name, "B", 8)
        self.set_fill_color(30, 60, 120)
        self.set_text_color(255, 255, 255)
        for i, h in enumerate(headers):
            self.cell(col_widths[i], 8, h, border=1, fill=True, align="C")
        self.ln()
        self.set_text_color(0, 0, 0)

        # Rows
        self.set_font(self._font_name, "", 8)
        fill = False
        for row in rows:
            if fill:
                self.set_fill_color(245, 248, 252)
            h = 7
            for i, val in enumerate(row):
                w = col_widths[i] if i < len(col_widths) else col_widths[-1]
                self.cell(w, h, str(val)[:40], border=1, fill=fill, align="C")
            self.ln()
            fill = not fill
        self.ln(4)

    def add_df_table(self, df, max_rows: int = 200):
        headers = list(df.columns)
        rows = df.head(max_rows).values.tolist()
        self.add_data_table(headers, rows)

    def add_formula(self, latex_str: str, description: str = ""):
        if description:
            self.set_font(self._font_name, "", 10)
            self.cell(0, 6, description, new_x="LMARGIN", new_y="NEXT")
            self.ln(1)
        try:
            img_bytes = _render_latex(latex_str)
            tmp = tempfile.NamedTemporaryFile(suffix=".png", delete=False)
            tmp.write(img_bytes)
            tmp.close()
            self._temp_files.append(Path(tmp.name))
            self.image(tmp.name, w=140)
            self.ln(3)
        except Exception:
            self.set_font(self._font_name, "", 8)
            self.multi_cell(0, 5, latex_str)
            self.set_font(self._font_name, "", 11)
            self.ln(3)

    def add_image_bytes(self, img_bytes: bytes, w: float = 180):
        tmp = tempfile.NamedTemporaryFile(suffix=".png", delete=False)
        tmp.write(img_bytes)
        tmp.close()
        self._temp_files.append(Path(tmp.name))
        self.image(tmp.name, w=w)
        self.ln(4)

    def save(self, filepath: str | Path):
        self.alias_nb_pages()
        self.output(str(filepath))
        for tmp in self._temp_files:
            try:
                tmp.unlink()
            except OSError:
                pass
        self._temp_files.clear()


# ═══════════════════════════════════════════════════════════════════════════
# Section renderers
# ═══════════════════════════════════════════════════════════════════════════

def _s(key: str, lang: str) -> str:
    return get_string(key, lang)


def _sec_model_settings(pdf: EnglishPDF, data: ReportData, lang: str):
    """Render model settings JSON as well-categorized tables."""
    pdf.add_page()
    pdf.add_heading("Model Settings", 1)
    ms = data.model_settings
    if not ms:
        pdf.add_paragraph(_s("NOT_AVAILABLE", lang))
        return

    # ── 1. Project Information ────────────────────────────────────────
    pdf.add_heading("Project Information", 2)
    info_rows = [
        ("Province", ms.get("ostan", "")),
        ("City", ms.get("city", "")),
        ("Relative Risk Level", _en_risk(ms.get("risk_level", ""))),
        ("Soil Type", _en_soil(ms.get("soil_type", ""))),
        ("Importance Factor", ms.get("importance_factor", "")),
    ]
    pdf.add_kv_table([(k, str(v)) for k, v in info_rows if v])

    # ── 2. Gravity Loads ──────────────────────────────────────────────
    pdf.add_heading("Gravity Loads", 2)
    _load_map = [
        ("Dead Load (DL)", "dead_combobox"),
        ("Super Dead Load (SD)", "sdead_combobox"),
        ("Partition Dead", "partition_dead_combobox"),
        ("Live Load", "live_combobox"),
        ("Reducible Live", "lred_combobox"),
        ("Parking Live", "live_parking_combobox"),
        ("Partition Live", "partition_live_combobox"),
        ("Live Load 0.5", "live5_combobox"),
        ("Reducible Live 0.5", "lred5_combobox"),
        ("Roof Live", "lroof_combobox"),
        ("Mass", "mass_combobox"),
        ("Vertical Seismic (EV)", "ev_combobox"),
        ("Modal", "modal_combobox"),
    ]
    load_rows = [(label, ms.get(key, "")) for label, key in _load_map]
    pdf.add_kv_table([(k, str(v)) for k, v in load_rows if v])

    # Retaining wall loads
    if ms.get("retaining_wall_groupbox"):
        pdf.add_heading("Retaining Wall Loads", 3)
        rw_rows = [
            ("Lateral Soil Pressure X+", ms.get("hxp_combobox", "")),
            ("Lateral Soil Pressure X-", ms.get("hxn_combobox", "")),
            ("Lateral Soil Pressure Y+", ms.get("hyp_combobox", "")),
            ("Lateral Soil Pressure Y-", ms.get("hyn_combobox", "")),
        ]
        pdf.add_kv_table([(k, str(v)) for k, v in rw_rows if v])

    # ── 3. Structural System (Primary) ────────────────────────────────
    _sys_label = "Structural System" if not ms.get("activate_second_system") else "Structural System (Lower)"
    pdf.add_heading(_sys_label, 2)
    sys_rows = [
        ("X System", ms.get("x_system_name", "")),
        ("X Lateral System", ms.get("x_lateral_name", "")),
        ("Ru (X)", str(ms.get("Rux", ""))),
        ("Cd (X)", str(ms.get("cdx", ""))),
        ("Y System", ms.get("y_system_name", "")),
        ("Y Lateral System", ms.get("y_lateral_name", "")),
        ("Ru (Y)", str(ms.get("Ruy", ""))),
        ("Cd (Y)", str(ms.get("cdy", ""))),
        ("Bottom Story", ms.get("bot_x_combo", "")),
        ("Top Story", ms.get("top_x_combo", "")),
        ("Top Story for Height", ms.get("top_story_for_height", "")),
        ("Number of Stories", str(ms.get("no_of_story_x", ""))),
        ("Building Height (m)", str(ms.get("height_x", ""))),
        ("Infill Panel", "Yes" if ms.get("infill") else "No"),
    ]
    pdf.add_kv_table([(k, v) for k, v in sys_rows if v and v != "None"])

    # ── 4. Structural System (Secondary) ──────────────────────────────
    if ms.get("activate_second_system"):
        pdf.add_heading("Structural System (Upper)", 2)
        sys2_rows = [
            ("X System", ms.get("x_system_name_1", "")),
            ("X Lateral System", ms.get("x_lateral_name_1", "")),
            ("Ru (X)", str(ms.get("Rux1", ""))),
            ("Cd (X)", str(ms.get("cdx1", ""))),
            ("Y System", ms.get("y_system_name_1", "")),
            ("Y Lateral System", ms.get("y_lateral_name_1", "")),
            ("Ru (Y)", str(ms.get("Ruy1", ""))),
            ("Cd (Y)", str(ms.get("cdy1", ""))),
            ("Bottom Story", ms.get("bot_x1_combo", "")),
            ("Top Story", ms.get("top_x1_combo", "")),
            ("Top Story for Height", ms.get("top_story_for_height1", "")),
            ("Number of Stories", str(ms.get("no_of_story_x1", ""))),
            ("Building Height (m)", str(ms.get("height_x1", ""))),
            ("Infill Panel", "Yes" if ms.get("infill_1") else "No"),
            ("Stiffness 10x", "Yes" if ms.get("special_case") else "No"),
        ]
        pdf.add_kv_table([(k, v) for k, v in sys2_rows if v and v != "None"])

    # ── 5. Static Earthquake Load Cases ───────────────────────────────
    pdf.add_heading("Static Earthquake Load Cases", 2)
    eq_header = ["Load Case", "X Direction", "Y Direction"]
    eq_rows = [
        ["EQ without Eccentricity", ms.get("ex_combobox", ""), ms.get("ey_combobox", "")],
        ["EQ + Positive Eccentricity", ms.get("exp_combobox", ""), ms.get("eyp_combobox", "")],
        ["EQ + Negative Eccentricity", ms.get("exn_combobox", ""), ms.get("eyn_combobox", "")],
        ["EQ Drift (no eccentricity)", ms.get("ex_drift_combobox", ""), ms.get("ey_drift_combobox", "")],
        ["EQ Drift + Positive Ecc.", ms.get("exp_drift_combobox", ""), ms.get("eyp_drift_combobox", "")],
        ["EQ Drift + Negative Ecc.", ms.get("exn_drift_combobox", ""), ms.get("eyn_drift_combobox", "")],
    ]
    eq_rows = [r for r in eq_rows if r[1] or r[2]]
    if eq_rows:
        pdf.add_data_table(eq_header, eq_rows)

    rho_rows = [
        ("Redundancy Factor (rho) X", ms.get("rhox_combobox", "")),
        ("Redundancy Factor (rho) Y", ms.get("rhoy_combobox", "")),
    ]
    pdf.add_kv_table([(k, str(v)) for k, v in rho_rows if v])

    # Second system earthquake load cases
    if ms.get("activate_second_system"):
        pdf.add_heading("Static EQ Load Cases (Upper System)", 3)
        eq2_rows = [
            ["EQ without Eccentricity", ms.get("ex1_combobox", ""), ms.get("ey1_combobox", "")],
            ["EQ + Positive Eccentricity", ms.get("exp1_combobox", ""), ms.get("eyp1_combobox", "")],
            ["EQ + Negative Eccentricity", ms.get("exn1_combobox", ""), ms.get("eyn1_combobox", "")],
            ["EQ Drift (no eccentricity)", ms.get("ex1_drift_combobox", ""), ms.get("ey1_drift_combobox", "")],
            ["EQ Drift + Positive Ecc.", ms.get("exp1_drift_combobox", ""), ms.get("eyp1_drift_combobox", "")],
            ["EQ Drift + Negative Ecc.", ms.get("exn1_drift_combobox", ""), ms.get("eyn1_drift_combobox", "")],
        ]
        eq2_rows = [r for r in eq2_rows if r[1] or r[2]]
        if eq2_rows:
            pdf.add_data_table(eq_header, eq2_rows)

    # ── 6. Dynamic Analysis ───────────────────────────────────────────
    if ms.get("dynamic_analysis_groupbox"):
        pdf.add_heading("Dynamic Analysis", 2)
        pdf.add_paragraph(
            f"X Scale Factor: {ms.get('x_scalefactor_combobox', '')}, "
            f"Y Scale Factor: {ms.get('y_scalefactor_combobox', '')}"
        )
        if ms.get("combination_response_spectrum_checkbox"):
            dyn_header = ["Load Case", "X Direction", "Y Direction"]
            dyn_rows = [
                ["Spectral (no ecc.)", ms.get("sx_combobox", ""), ms.get("sy_combobox", "")],
                ["Spectral (with ecc.)", ms.get("sxe_combobox", ""), ms.get("sye_combobox", "")],
                ["Spectral Drift (no ecc.)", ms.get("sx_drift_combobox", ""), ms.get("sy_drift_combobox", "")],
                ["Spectral Drift (with ecc.)", ms.get("sxe_drift_combobox", ""), ms.get("sye_drift_combobox", "")],
            ]
            dyn_rows = [r for r in dyn_rows if r[1] or r[2]]
            if dyn_rows:
                pdf.add_data_table(dyn_header, dyn_rows)

    # ── 7. Analytical Periods ─────────────────────────────────────────
    pdf.add_heading("Analytical Periods", 2)
    period_rows = [
        ("T analytical X (s)", str(ms.get("tx_an", ""))),
        ("T analytical Y (s)", str(ms.get("ty_an", ""))),
    ]
    if ms.get("activate_second_system"):
        period_rows.extend([
            ("T analytical X - upper (s)", str(ms.get("tx1_an", ""))),
            ("T analytical Y - upper (s)", str(ms.get("ty1_an", ""))),
        ])
    pdf.add_kv_table([(k, v) for k, v in period_rows if v and v != "None"])

    # ── 8. Structural Material ────────────────────────────────────────
    material = "Concrete" if ms.get("concrete_radiobutton") else "Steel"
    pdf.add_heading("Structural Material", 2)
    pdf.add_kv_table([("Material", material)])

    # ── 9. Irregularities ─────────────────────────────────────────────
    pdf.add_heading("Irregularities", 2)

    pdf.add_heading("Plan Irregularities", 3)
    plan_items = []
    if ms.get("torsional_irregularity_groupbox"):
        if ms.get("extreme_torsion_irregular_checkbox"):
            plan_items.append(("Extreme Torsional Irregularity", True))
        elif ms.get("torsion_irregular_checkbox"):
            plan_items.append(("Torsional Irregularity", True))
    else:
        plan_items.append(("Torsional Irregularity", False))
    plan_items.extend([
        ("Re-entrant Corner", ms.get("reentrance_corner_checkbox", False)),
        ("Diaphragm Discontinuity", ms.get("diaphragm_discontinuity_checkbox", False)),
        ("Out-of-Plane Offset", ms.get("out_of_plane_offset_checkbox", False)),
        ("Non-Parallel System", ms.get("nonparallel_system_checkbox", False)),
    ])
    _pdf_checkbox_table(pdf, plan_items)

    pdf.add_heading("Vertical Irregularities", 3)
    vert_items = []
    if ms.get("stiffness_soft_story_groupbox"):
        if ms.get("extreme_stiffness_irregular_checkbox"):
            vert_items.append(("Extreme Soft Story", True))
        elif ms.get("stiffness_irregular_checkbox"):
            vert_items.append(("Soft Story", True))
    else:
        vert_items.append(("Stiffness Irregularity", False))
    vert_items.extend([
        ("Weight (Mass) Irregularity", ms.get("weight_mass_checkbox", False)),
        ("Geometric Irregularity", ms.get("geometric_checkbox", False)),
        ("In-Plane Discontinuity", ms.get("in_plane_discontinuity_checkbox", False)),
    ])
    if ms.get("lateral_strength_weak_story_groupbox"):
        if ms.get("extreme_strength_irregular_checkbox"):
            vert_items.append(("Extreme Weak Story", True))
        elif ms.get("strength_irregular_checkbox"):
            vert_items.append(("Weak Story", True))
    else:
        vert_items.append(("Lateral Strength Irregularity", False))
    _pdf_checkbox_table(pdf, vert_items)


def _pdf_checkbox_table(pdf: EnglishPDF, items: list[tuple[str, bool]]):
    """Render a checkbox list with ASCE 7-16 descriptions for detected irregularities."""
    rows = []
    for label, checked in items:
        mark = "\u2713" if checked else "\u2610"
        rows.append([f"{mark}  {label}"])
    pdf.add_data_table(["Irregularity Check"], rows)

    # Add ASCE 7-16 penalty descriptions for each detected irregularity
    detected = [label for label, checked in items if checked]
    if detected:
        pdf.ln(2)
        pdf.add_heading("ASCE 7-16 Irregularity Descriptions", 4)
        for label in detected:
            desc = ASCE7_IRREGULARITY_DESC.get(label)
            if desc:
                pdf.add_paragraph(f"{label}:", bold=True)
                pdf.add_paragraph(desc)


def _sec_project_info(pdf: EnglishPDF, data: ReportData, lang: str):
    pdf.add_page()
    pdf.add_heading(_s("PROJECT_INFO", lang), 1)
    b = data.building
    rows = [
        (_s("PROJECT_INFO", lang), data.project_name),
        (_s("CITY", lang), data.location),
        (_s("NO_STORIES", lang), str(len(data.stories))),
        (_s("HEIGHT_METER", lang), f"{data.total_height:.1f}"),
    ]
    if b:
        rows.extend([
            (_s("SOIL_TYPE", lang), _en_soil(getattr(b, "soil_type", ""))),
            (_s("RISK_LEVEL", lang), _en_risk(getattr(b, "risk_level", ""))),
            (_s("IMPORTANCE_FACTOR", lang), str(getattr(b, "importance_factor", ""))),
            (_s("DESIGN_BASE_ACCELERATION", lang), str(getattr(b, "acc", ""))),
        ])
    pdf.add_kv_table(rows)


def _sec_structural_system(pdf: EnglishPDF, data: ReportData, lang: str):
    pdf.add_page()
    pdf.add_heading(_s("STRUCTURAL_SYSTEM", lang), 1)
    b = data.building
    if not b:
        pdf.add_paragraph(_s("NOT_AVAILABLE", lang))
        return
    for direction, sys_attr in [("X", "x_system"), ("Y", "y_system")]:
        sys = getattr(b, sys_attr, None)
        if sys is None:
            continue
        pdf.add_heading(f"{_s(direction + '_DIRECTION', lang)}", 2)
        rows = [
            (_s("RU_FACTOR", lang), str(getattr(sys, "Ru", ""))),
            (_s("PHI0_FACTOR", lang), str(getattr(sys, "phi0", ""))),
            (_s("CD_FACTOR", lang), str(getattr(sys, "cd", ""))),
            (_s("MAX_HEIGHT", lang), str(getattr(sys, "max_height", ""))),
        ]
        pdf.add_kv_table(rows)


def _sec_seismic_params(pdf: EnglishPDF, data: ReportData, lang: str):
    pdf.add_page()
    pdf.add_heading(_s("SEISMIC_PARAMS", lang), 1)
    b = data.building
    if not b:
        pdf.add_paragraph(_s("NOT_AVAILABLE", lang))
        return
    rows = [
        (_s("SOIL_TYPE", lang), _en_soil(getattr(b, "soil_type", ""))),
        (_s("RISK_LEVEL", lang), _en_risk(getattr(b, "risk_level", ""))),
        (_s("DESIGN_BASE_ACCELERATION", lang), str(getattr(b, "acc", ""))),
        (_s("IMPORTANCE_FACTOR", lang), str(getattr(b, "importance_factor", ""))),
        (_s("NO_STORIES", lang), str(getattr(b, "number_of_story", len(data.stories)))),
        (_s("HEIGHT_METER", lang), f"{getattr(b, 'height', data.total_height):.1f}"),
    ]
    pdf.add_kv_table(rows)


def _sec_earthquake_formulation(pdf: EnglishPDF, data: ReportData, lang: str):
    pdf.add_page()
    pdf.add_heading(_s("EARTHQUAKE_COEFFICIENT_CALC", lang), 1)
    b = data.building
    if not b:
        pdf.add_paragraph(_s("NOT_AVAILABLE", lang))
        return
    try:
        from civiltools.report.latex_str import full_earthquake_calculation
        from civiltools.report.docx_report import _building_to_seismic_dict
        sp = _building_to_seismic_dict(b, "x")
        if sp:
            pdf.add_heading(_s("X_DIRECTION", lang), 2)
            for desc, latex in full_earthquake_calculation(sp, "x"):
                pdf.add_formula(latex, description=desc)
    except Exception:
        pdf.add_paragraph("Earthquake formulas could not be generated.")


def _sec_earthquake_values(pdf: EnglishPDF, data: ReportData, lang: str):
    pdf.add_page()
    pdf.add_heading("Earthquake Coefficient Values", 1)
    b = data.building
    if not b:
        pdf.add_paragraph(_s("NOT_AVAILABLE", lang))
        return
    try:
        from civiltools.report.latex_str import full_earthquake_calculation
        from civiltools.report.docx_report import _building_to_seismic_dict
        sp = _building_to_seismic_dict(b, "y")
        if sp:
            pdf.add_heading(_s("Y_DIRECTION", lang), 2)
            for desc, latex in full_earthquake_calculation(sp, "y"):
                pdf.add_formula(latex, description=desc)
    except Exception:
        pdf.add_paragraph("Earthquake formulas could not be generated.")

    if b and hasattr(b, "results") and b.results:
        _, cx, cy = b.results
        pdf.add_heading("Coefficient Summary", 2)
        pdf.add_data_table(
            ["Direction", "C"],
            [["X", f"{cx:.4f}"], ["Y", f"{cy:.4f}"]],
        )


def _sec_load_combinations(pdf: EnglishPDF, data: ReportData, lang: str):
    pdf.add_page()
    pdf.add_heading(_s("LOAD_COMBINATIONS", lang), 1)
    if data.load_combinations is None or data.load_combinations.empty:
        pdf.add_paragraph(_s("NOT_AVAILABLE", lang))
        return

    df = data.load_combinations
    combo_names = df["Name"].unique()
    pdf.add_paragraph(
        f"Total of {len(combo_names)} load combinations defined in the model."
    )

    # Build one-line format: "ComboName: SF1(Load1) + SF2(Load2) + ..."
    rows = []
    for name in combo_names:
        sub = df[df["Name"] == name]
        parts = []
        for _, r in sub.iterrows():
            sf = r.get("SF", 1)
            load = r.get("LoadName", r.get("Load", ""))
            try:
                sf_val = float(sf)
                if sf_val == 1.0:
                    parts.append(str(load))
                elif sf_val == -1.0:
                    parts.append(f"-{load}")
                else:
                    parts.append(f"{sf_val:g}({load})")
            except (ValueError, TypeError):
                parts.append(f"{sf}({load})")
        formula = " + ".join(parts).replace("+ -", "- ")
        rows.append([name, formula])

    pdf.add_data_table(["Combination", "Definition"], rows)


def _sec_story_forces(pdf: EnglishPDF, data: ReportData, lang: str):
    pdf.add_page()
    pdf.add_heading(_s("STORY_FORCES", lang), 1)
    if not data.story_forces_data or not data.story_forces_fields:
        pdf.add_paragraph(_s("NOT_AVAILABLE", lang))
        return
    pdf.add_paragraph(
        "Story forces from seismic load patterns with percentage of base shear."
    )
    pdf.add_data_table(data.story_forces_fields, data.story_forces_data)


def _sec_drift(pdf: EnglishPDF, data: ReportData, lang: str):
    pdf.add_page()
    pdf.add_heading(_s("STORY_DRIFT", lang), 1)
    if data.drift_data is None or data.drift_data.empty:
        pdf.add_paragraph(_s("NOT_AVAILABLE", lang))
        return
    pdf.add_paragraph(
        "Maximum story drift vs. allowable limits."
    )
    pdf.add_df_table(data.drift_data)


def _sec_torsion(pdf: EnglishPDF, data: ReportData, lang: str):
    pdf.add_page()
    pdf.add_heading(_s("TORSIONAL_IRREGULARITY", lang), 1)
    if data.torsion_data is None or data.torsion_data.empty:
        pdf.add_paragraph(_s("NOT_AVAILABLE", lang))
        return
    pdf.add_paragraph(
        "Ratio of max to avg diaphragm drift. Ratio > 1.2 = torsional irregularity."
    )
    pdf.add_df_table(data.torsion_data)


def _sec_pmm_columns(pdf: EnglishPDF, data: ReportData, lang: str):
    pdf.add_page()
    pdf.add_heading(_s("PMM_COLUMNS", lang), 1)
    if data.pmm_data is None or data.pmm_data.empty:
        pdf.add_paragraph(_s("NOT_AVAILABLE", lang))
        return
    pdf.add_paragraph("Concrete column PMM interaction ratios.")
    pdf.add_df_table(data.pmm_data)


def _sec_story_plans(pdf: EnglishPDF, data: ReportData, lang: str):
    pdf.add_heading(_s("STORY_PLANS", lang), 1)
    if not data.story_plan_images:
        pdf.add_paragraph(_s("NOT_AVAILABLE", lang))
        return
    pdf.add_paragraph("Beam & column plans with section names.")
    for story in data.stories:
        img = data.story_plan_images.get(story)
        if img:
            pdf.add_page()
            pdf.add_heading(f"Story: {story}", 2)
            pdf.add_image_bytes(img, w=175)


def _sec_area_loads(pdf: EnglishPDF, data: ReportData, lang: str):
    pdf.add_heading(_s("AREA_LOAD_PLANS", lang), 1)
    if not data.area_load_images:
        pdf.add_paragraph(_s("NOT_AVAILABLE", lang))
        return

    pdf.add_paragraph(
        "Floor area load plans for each story. Areas with identical "
        "load patterns are grouped and colour-coded."
    )
    for story in data.stories:
        img = data.area_load_images.get(story)
        if img:
            pdf.add_page()
            pdf.add_heading(f"Story: {story}", 2)
            pdf.add_image_bytes(img, w=175)

            # Per-story load set table
            story_areas = data.area_data.get(story, [])
            story_sets = sorted({a.load_set for a in story_areas})
            if story_sets and data.load_set_defs:
                headers = ["Load Set", "Load Patterns (kg/m\u00b2)"]
                rows = []
                for sname in story_sets:
                    lsd = data.load_set_defs.get(sname)
                    if lsd:
                        desc = ", ".join(
                            f"{p} = {v:.0f}" for p, v in lsd.loads.items()
                        )
                    else:
                        desc = ""
                    rows.append([sname, desc])
                pdf.add_data_table(headers, rows)


def _sec_joint_shear(pdf: EnglishPDF, data: ReportData, lang: str):
    pdf.add_page()
    pdf.add_heading("Joint Shear Check", 1)
    if data.joint_shear_data is None or data.joint_shear_data.empty:
        pdf.add_paragraph(_s("NOT_AVAILABLE", lang))
        return
    pdf.add_paragraph("Beam-column joint shear check results.")
    pdf.add_df_table(data.joint_shear_data)


# ═══════════════════════════════════════════════════════════════════════════
# Section dispatch
# ═══════════════════════════════════════════════════════════════════════════

_SECTION_DISPATCH = {
    "model_settings":         _sec_model_settings,
    "project_info":           _sec_project_info,
    "structural_system":      _sec_structural_system,
    "seismic_params":         _sec_seismic_params,
    "earthquake_formulation": _sec_earthquake_formulation,
    "earthquake_values":      _sec_earthquake_values,
    "load_combinations":      _sec_load_combinations,
    "story_forces":           _sec_story_forces,
    "drift":                  _sec_drift,
    "torsion":                _sec_torsion,
    "joint_shear":            _sec_joint_shear,
    "pmm_columns":            _sec_pmm_columns,
    "story_plans":            _sec_story_plans,
    "area_loads":             _sec_area_loads,
}


# ═══════════════════════════════════════════════════════════════════════════
# High-level builder
# ═══════════════════════════════════════════════════════════════════════════

def create_pdf_report(
    data: ReportData,
    config: ReportConfig | None = None,
    output_path: str | Path | None = None,
) -> Path:
    """Generate a full PDF report from extracted data.

    Parameters
    ----------
    data : ReportData
        All report data (from ``extract_report_data``).
    config : ReportConfig, optional
        Report configuration.
    output_path : str | Path, optional
        Output file path.
    """
    config = config or ReportConfig(language="en")
    lang = config.language if config.language != "both" else "en"
    pdf = EnglishPDF(config)
    pdf.alias_nb_pages()

    # Title page
    title = data.project_name or "Structural Report"
    pdf.add_title_page(title, "Structural Engineering Report")

    # Sections
    for section_key in config.active_sections:
        renderer = _SECTION_DISPATCH.get(section_key)
        if renderer:
            renderer(pdf, data, lang)
        else:
            pdf.add_page()
            pdf.add_heading(config.get_section_name(section_key), 1)
            pdf.add_paragraph(f"[Section: {section_key} - content pending]")

    # Save
    if output_path is None:
        stem = (data.project_name or "report").replace(" ", "_")
        output_path = Path(f"{stem}_report.pdf")
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    pdf.save(output_path)
    return output_path
